name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *"   # sync every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Mohid-Abbas/MadniWoodenLegacy.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
